alias ll="ls -alh"
export DEV_DIR="/dev_exclusions"
alias dev="cd $DEV_DIR"
alias desk="cd $DEV_DIR/desk"
alias rainbow="cd $DEV_DIR/rainbowbridge"
alias start_es="elasticsearch --config=/usr/local/opt/elasticsearch17/config/elasticsearch.yml"
alias webclient="cd $DEV_DIR/webclient"
alias be="bundle exec"
